version: '3.7'

services:
  testtemplate2.migrations:
    # image: ${DOCKER_REGISTRY-}testtemplate2sql
    env_file: .env
    build:
      context: .
      dockerfile: src/TestTemplate2.Migrations/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"